version: "3.8"
services:
  backend:
    image: "lcxustc/springboot-react-fullstack:6.1.2023.4.6.31"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev