version: "3.8"
services:
  backend:
    image: "lcxustc/springboot-react-fullstack:4.5.2023.23.40.49"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev