version: "3.8"
services:
  backend:
    image: "lcxustc/springboot-react-fullstack:7.5.2023.20.15.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev